import json
import os

def sync_zh():
    fr_path = 'composeApp/src/commonMain/resources/strings_fr.json'
    zh_path = 'composeApp/src/commonMain/resources/strings_zh.json'
    
    with open(fr_path, 'r', encoding='utf-8') as f:
        fr_data = json.load(f)
        
    translations = {
        # Core & General
        "welcome": "欢迎",
        "loading": "加载中...",
        "save": "保存",
        "update": "更新",
        "remove": "移除",
        "calculate": "计算",
        "export": "导出",
        "import": "导入",
        "general.importing": "正在导入...",
        "general.importSuccess": "导入成功！",
        "general.error": "错误",
        "general.or": "- 或 -",
        "general.create": "创建",
        "general.success": "成功",
        "progress": "进度",
        "general.none": "无",
        "general.close": "关闭",
        "general.unitYear": "岁",
        "general.unitYears": "岁",
        "general.unitMonth": "月",
        "general.measureDate": "测量日期",
        "general.selectPlaceholder": "请选择...",
        "general.expand": "展开",
        "general.totalElements": "元素总数：",
        "general.today": "今天",
        "general.appName": "VetNutri MP",
        "general.cancel": "取消",
        "general.ok": "确定",
        "general.delete": "删除",
        "general.edit": "编辑",
        "general.add": "添加",
        "general.search": "搜索",
        "general.validate": "验证",
        "general.confirm": "确认",
        "general.save": "保存",
        "general.reduce": "折叠",
        
        # Animal
        "animal.name": "名称",
        "animal.species": "物种",
        "animal.sex": "性别",
        "animal.breed": "品种",
        "animal.id": "ID",
        "animal.owner": "业主",
        "animal.description": "描述",
        "animal.weight": "体重",
        "animal.age": "年龄",
        "animal.birthDate": "出生日期",
        "animal.summary": "摘要",
        "animal.sterilized": "已绝育",
        "animal.dead": "已去世",
        "animal.edit": "编辑动物",
        "animal.new": "新动物",
        
        # Species
        "species.dog": "狗",
        "species.cat": "猫",
        "species.horse": "马",
        "species.ferret": "雪貂",
        "species.wildCanine": "野生犬科",
        "species.wildFeline": "野生猫科",
        "species.folivore": "食叶动物",
        
        # Enums Species
        "enum.Espece.DOG": "狗",
        "enum.Espece.CAT": "猫",
        "enum.Espece.PRIMATE": "灵长类",
        "enum.Espece.RAT": "大鼠",
        "enum.Espece.SOURIS": "小鼠",
        "enum.Espece.FURET": "雪貂",
        "enum.Espece.LAPIN": "兔子",
        "enum.Espece.CHEVAL": "马",
        
        # Sex Enums
        "enum.Sex.MALE_ENTIER": "公（未去势）",
        "enum.Sex.MALE_CASTRE": "公（已去势）",
        "enum.Sex.FEMELLE_ENTIERE": "母（未绝育）",
        "enum.Sex.FEMELLE_STERILISEE": "母（已绝育）",
        
        # Nutrition
        "nutrition.proteins": "蛋白质",
        "nutrition.lipids": "脂肪",
        "nutrition.carbohydrates": "碳水化合物",
        "nutrition.fiber": "纤维",
        "nutrition.moisture": "水分",
        "nutrition.ash": "粗灰分",
        "nutrition.energy": "能量",
        "nutrition.dryMatter": "干物质",
        
        # Minerals & Vitamins (partial)
        "minerals.calcium": "钙",
        "minerals.phosphorus": "磷",
        "minerals.magnesium": "镁",
        "minerals.sodium": "钠",
        "minerals.potassium": "钾",
        
        # Units
        "units.kilogram": "kg",
        "units.gram": "g",
        "units.milligram": "mg",
        "units.microgram": "µg",
        "units.percentage": "%",
        "units.kcal": "kcal",
        
        # Consultation
        "consultation.date": "日期",
        "consultation.objective": "目标",
        "consultation.title": "咨询",
        "consultation.none": "无咨询记录",
        "consultation.add": "添加咨询",
        
        # Database & Update
        "database.status.checking": "正在检查...",
        "database.status.complete": "数据库完整",
        "database.status.incomplete": "数据库不完整",
        "database.action.updating": "正在更新...",
        "update.action.later": "稍后",
        "update.install_now": "立即安装",
        "update.new": "新版本：",
        
        # Startup & Settings
        "startup.title": "VetNutri",
        "startup.subtitle": "专业宠物营养助手",
        "startup.version": "版本: %1$s",
        "startup.loading": "正在加载数据...",
        "startup.continue": "继续",
        "startup.checking_updates": "正在检查更新...",
        
        "settings.title": "设置",
        "settings.language": "语言",
        "settings.language.fr": "法语",
        "settings.language.en": "英语",
        "settings.language.zh": "中文",
        "settings.displaySettings": "显示设置",
        "settings.uiScale": "界面缩放",
        "settings.debugMode": "调试模式",
        "settings.close": "关闭",
        
        # Food
        "food.list.title": "食物列表",
        "animalList.foodList": "食物列表",
        
        # Terms
        "terms.accept_button": "我接受条款",
        "terms.accepted": "已接受一般条款",
        "terms.full_title": "一般使用条款",
        
        # NewReference
        "new_reference.title_new": "新参考资料",
        "new_reference.title_edit": "编辑参考资料",
        "new_reference.tab.info": "信息",
        "new_reference.tab.nutrients": "营养成分",
        "new_reference.tab.equations": "方程",
        "new_reference.tab.complementary": "补充",
        "new_reference.tab.coefficients": "系数",
        "new_reference.field.name": "参考名称",
        "new_reference.field.description": "描述",
        "new_reference.field.species": "物种",
        "new_reference.field.physio_stage": "生理阶段",
        "new_reference.field.is_complementary": "是补充参考",
        "new_reference.field.complementary_need": "补充需求名称",
        "new_reference.field.energy_name": "能量名称",
        "new_reference.field.consistency": "一致性: %1$s",
        "new_reference.nutrient_category.macro": "宏量营养素",
        "new_reference.nutrient_category.minerals": "主要矿物质",
        "new_reference.nutrient_category.oligo": "微量元素",
        "new_reference.nutrient_category.vitamins": "维生素",
        "new_reference.nutrient_category.lipids": "脂质",
        "new_reference.nutrient_category.aa": "氨基酸",
        "new_reference.nutrient_category.others": "其他营养素",
        "new_reference.nutrient_category.analysis": "计算分析",
        "new_reference.refresh_equations": "刷新方程",
        "new_reference.maladie_warning_title": "疾病参考",
        "new_reference.maladie_warning_desc": "能量、能量密度和代谢体重方程不适用于疾病相关参考。",
        "new_reference.eq_enercomp_title": "ENERCOMP 方程（补充需求）",
        "new_reference.select_equation": "选择一个方程",
        "new_reference.eq_metabolic_weight": "代谢体重方程",
        "new_reference.eq_none": "无方程",
        "new_reference.eq_bee": "基础能量消耗方程",
        "new_reference.eq_decom": "消化能方程（复合食品）",
        "new_reference.eq_deraw": "消化能方程（原始食品）",
        "new_reference.complementary_eq_title": "补充营养方程",
        "new_reference.complementary_eq_none": "没有可用于 %1$s 的补充方程。",
        "new_reference.nutrient_species_footer": "营养素: %1$s · 物种: %2$s",
        "new_reference.all_species": "所有物种",
        "new_reference.remove_association": "移除",
        "new_reference.add_association": "关联",
        "new_reference.maladie_coeff_warning": "系数不适用于疾病相关参考。",
        "new_reference.coeff_normal": "正常",
        "new_reference.not_defined": "未定义",
        "new_reference.biblio_ref_prefix": "参考: %1$s",
        "new_reference.edit_nutrient_title": "编辑 %1$s",
        "new_reference.edit_available_physical_units": "可用物理单位: %1$s",
        "new_reference.biblio_placeholder": "文档",
        "new_reference.coeff_group_prefix": "组 %1$s",
        "food_edit.title_add": "添加食物",
        "food_edit.title_edit": "编辑食物",
        "food_edit.tab.general": "常规信息",
        "food_edit.tab.nutrition": "营养成分",
        "food_edit.success_save": "食物保存成功",
        "food_edit.error.name_required": "必须填写食物名称",
        "food_edit.error.species_required": "请至少选择一种物种",
        "food_edit.error.nutrients_invalid": "某些营养值无效",
        "food_edit.error.save_failed": "保存时出错: %1$s",
        "food_edit.field.name": "食物名称",
        "food_edit.field.brand": "品牌",
        "food_edit.field.gamme": "系列",
        "food_edit.field.database": "数据库",
        "food_edit.field.price": "价格",
        "food_edit.field.price_category": "价格类别",
        "food_edit.field.quantity": "数量",
        "food_edit.field.consistent": "一致的食物",
        "food_edit.field.type_class": "类型与分类",
        "food_edit.field.ingredients": "配料",
        "food_edit.field.ingredients_list": "成品配料表",
        "food_edit.field.compatible_species": "适用物种",
        "food_edit.field.indications": "适应症",
        "food_edit.field.cont": "容器",
        "food_edit.hint.select_type": "选择食物类型",
        "food_edit.hint.select_group": "选择食物组",
        "food_edit.hint.select_cont": "选择一个容器",
        "food_edit.section.main_nutrients": "主要营养素",
        "food_edit.section.lipids": "脂类",
        "food_edit.section.macronutrients": "常量营养素",
        "food_edit.section.minerals": "矿物质",
        "food_edit.section.vitamins": "维生素",
        "food_edit.section.amino_acids": "氨基酸",
        "food_edit.section.other_nutrients": "其他营养素",
        "new_reference.group_name_label": "群组名称",
        "new_reference.edit_group_name": "编辑名称",
        "new_reference.add_coef": "添加系数",
        "new_reference.coef_unnamed": "未命名",
        "new_reference.coef_value_label": "系数: %1$s",
        "new_reference.add_coef_title": "添加系数",
        "new_reference.error_empty_desc": "描述不能为空",
        "new_reference.error_invalid_coef": "系数必须是有效数字",
        "new_reference.confirm_delete_title": "确认删除",
        "new_reference.confirm_delete_text": "您确定要删除此系数吗？",
        "new_reference.button_delete_coef": "删除此系数",
        "new_reference.edit_coef_title": "编辑系数",
        "enum.Reflevel.MIN": "最小值",
        "enum.Reflevel.MAX": "最大值",
        "enum.Reflevel.OPTIMIN": "最佳最小值",
        "enum.Reflevel.OPTIMAX": "最佳最大值",
        
        # Preferences
        "preferences.title": "首选项",
        "preferences.species_title": "物种：",
        "preferences.selected_species": "已选物种",
        "preferences.choose_species": "选择一个物种",
        "preferences.available_species": "可用物种",
        "preferences.preferences_for": "%1$s 的首选项",
        "preferences.energy_expression": "能量表示方案：%1$s",
        "preferences.selected_nutrients_count": "已选养分：%1$d",
        "preferences.complementary_equations": "补充营养方程",
        "preferences.no_complementary_equations": "无可用补充方程",
        "preferences.no_equation": "无方程",
        "preferences.equation": "方程",
        "preferences.customize_desc": "为此物种自定义能量表示和显示的养分",
        "preferences.energy_expression_section": "能量表示方案",
        "preferences.current_selection": "当前选择：%1$s",
        "preferences.unit_label": "单位：%1$s",
        "preferences.complementary_equations_title": "补充营养素方程",
        "preferences.select_equations_desc": "选择用于计算此物种补充营养素的方程",
        "preferences.auto_save": "自动保存",
        "preferences.auto_save_desc": "所有更改将自动保存，并在下次启动时恢复。",
        "preferences.nutrients_selected_format": "已选择 %1$d/%2$d 个养分",
        
        # Nutrient Category
        "nutrient_category.base.name": "宏量营养素",
        "nutrient_category.base.desc": "蛋白质、脂质、碳水化合物、纤维、能量",
        "nutrient_category.macro.name": "基本矿物质",
        "nutrient_category.macro.desc": "钙、磷、钠、钾、镁、氯",
        "nutrient_category.min.name": "微量元素",
        "nutrient_category.min.desc": "铁、锌、铜、锰、碘、硒",
        "nutrient_category.vitam.name": "维生素",
        "nutrient_category.vitam.desc": "脂溶性和水溶性维生素",
        "nutrient_category.lipid.name": "脂肪酸",
        "nutrient_category.lipid.desc": "饱和、单不饱和、多不饱和脂肪酸",
        "nutrient_category.ama.name": "氨基酸",
        "nutrient_category.ama.desc": "必需和非必需氨基酸",
        "nutrient_category.ana.name": "分析与比率",
        "nutrient_category.ana.desc": "比率和营养分析",
        "nutrient_category.other.name": "其他养分",
        "nutrient_category.other.desc": "牛磺酸、肉碱、益生元",
        "nutrient_category.energie.name": "能量",
        "nutrient_category.energie.desc": "能量密度和代谢"
    }
    
    zh_data = {}
    zh_data["translations"] = {}
    
    for key, value in fr_data["translations"].items():
        if key in translations:
            zh_data["translations"][key] = translations[key]
        else:
            zh_data["translations"][key] = value
            
    with open(zh_path, 'w', encoding='utf-8') as f:
        json.dump(zh_data, f, ensure_ascii=False, indent=4)

if __name__ == "__main__":
    sync_zh()
