
ash = Ash

calcium = Calcium

fatCrude = Crude fats

fiberCrude = Crude fibers

insolFiber = Insoluble fiber

iron = Iron

magnesium = Magnesium

phosphorus = Phosphorus

potassium = Potassium

protein = Protein

proteinCrude = Crude proteins

sodium = Sodium

solFiber = Soluble fiber

starch = Starch

sugar = Sugars

totDietFiber = Total dietary fiber
