package fr.vetbrain.vetnutri_mp.Utils

import fr.vetbrain.vetnutri_mp.Enumer.Espece

object RaceCodeMapper {
    private val catRaceMap =
            mapOf(
                    "A1" to "Sibérien",
                    "A2" to "Snowshoe",
                    "A3" to "British shorthair",
                    "A4" to "Minskin",
                    "A5" to "Selkirk rex",
                    "A6" to "Anatoli",
                    "A7" to "Bengal",
                    "A8" to "Balinais",
                    "A9" to "Somali",
                    "A10" to "Turc de Van",
                    "A11" to "Highlander",
                    "A12" to "Brazilian shorthair",
                    "A13" to "Ojos azules",
                    "A14" to "Norvégien ou Skogkatt",
                    "A15" to "Siamois",
                    "A16" to "Cymric",
                    "A17" to "Ragamuffin",
                    "A18" to "Colorpoint shorthair",
                    "A19" to "American shorthair",
                    "A20" to "Ural rex",
                    "A21" to "Khao Manee",
                    "A22" to "Pixie-bob",
                    "A23" to "Bleu russe",
                    "A24" to "Seychellois",
                    "A25" to "Tiffany",
                    "A26" to "Exotic shorthair",
                    "A27" to "Cornish rex",
                    "A28" to "Serengeti",
                    "A29" to "Abyssin",
                    "A30" to "Safari",
                    "A31" to "Bombay",
                    "A32" to "Ragdoll",
                    "A33" to "Asian",
                    "A34" to "Thaï",
                    "A35" to "Maine coon",
                    "A36" to "Chartreux",
                    "A37" to "Californian spangled",
                    "A38" to "York chocolat",
                    "A39" to "LaPerm",
                    "A40" to "Savannah",
                    "A41" to "British longhair",
                    "A42" to "Korat",
                    "A43" to "Mau arabe",
                    "A44" to "Devon rex",
                    "A45" to "Manx",
                    "A46" to "Persan",
                    "A47" to "Bobtail des Kouriles",
                    "A48" to "Scottish fold",
                    "A49" to "Tonkinois",
                    "A50" to "European shorthair",
                    "A51" to "Bobtail américain",
                    "A52" to "Chantilly",
                    "A53" to "Donskoy",
                    "A54" to "American wirehair",
                    "A55" to "Oriental shorthair",
                    "A56" to "Burmese",
                    "A57" to "Mau égyptien",
                    "A58" to "Angora turc",
                    "A59" to "Ocicat",
                    "A60" to "Mandarin",
                    "A61" to "Chausie",
                    "A62" to "Munchkin",
                    "A63" to "Skookum",
                    "A64" to "Highland fold[11]",
                    "A65" to "American curl",
                    "A66" to "Sacré de Birmanie",
                    "A67" to "Brume australienne",
                    "A68" to "Himalayen",
                    "A69" to "Sokoké",
                    "A70" to "Havana brown",
                    "A71" to "Bobtail japonais",
                    "A72" to "German rex",
                    "A73" to "Peterbald",
                    "A74" to "Burmilla",
                    "A75" to "Nebelung",
                    "A76" to "Sphynx",
                    "A77" to "Singapura",
                    "A78" to "Toyger",
                    "A79" to "Californian rex",
                    "A80" to "Ceylan"
            )

    private val dogRaceMap =
            mapOf(
                    "A1" to "Dobermann",
                    "A2" to "Hovawart",
                    "A3" to "Beagle",
                    "A4" to "Terre-neuve",
                    "A5" to "Levrette italienne",
                    "A6" to "Bichon maltais",
                    "A7" to "Épagneul bleu de Picardie",
                    "A8" to "Brachet noir et feu",
                    "A9" to "Berger de Shiloh",
                    "A10" to "Chien d'arrêt allemand à poil long",
                    "A11" to "Braque d'Auvergne",
                    "A12" to "English Springer Spaniel",
                    "A13" to "Bouvier bernois",
                    "A14" to "Kangal Dog",
                    "A15" to "Bruno du Jura  - voir Chien courant suisse",
                    "A16" to "Chien d'arrêt allemand à poil raide",
                    "A17" to "Berger hollandais",
                    "A18" to "Dogue argentin",
                    "A19" to "Cocker Spaniel anglais",
                    "A20" to "Dingo",
                    "A21" to "Segugio Maremmano",
                    "A22" to "Terrier australien",
                    "A23" to "Lakeland Terrier",
                    "A24" to "Lévrier Chortaj",
                    "A25" to "Chien de Saint-Hubert",
                    "A26" to "Braque français",
                    "A27" to "Broholmer",
                    "A28" to "Épagneul de Pont-Audemer",
                    "A29" to "Berger du Larzac race disparue",
                    "A30" to "Pinscher autrichien",
                    "A31" to "Berger de la Crau",
                    "A32" to "Fila Brasileiro",
                    "A33" to "Berger de Beauce",
                    "A34" to "Mudi",
                    "A35" to "Terrier irlandais à poil doux",
                    "A36" to "Foxhound américain",
                    "A37" to "Terrier tibétain",
                    "A38" to "Chien Fila de Saint Miguel",
                    "A39" to "Kai",
                    "A40" to "Berger islandais",
                    "A41" to "Lévrier écossais",
                    "A42" to "Berger picard",
                    "A43" to "Petit chien lion",
                    "A45" to "Chien de Castro Laboreiro",
                    "A46" to "Terrier de chasse allemand",
                    "A47" to "Jouet fox terrier",
                    "A48" to "Tamaskan",
                    "A49" to "Rottweiler",
                    "A50" to "Berger Tahitien",
                    "A51" to "Grand Mansterlander",
                    "A52" to "Norfolk Terrier",
                    "A53" to "Basenji",
                    "A54" to "Chow-Chow",
                    "A55" to "Chien chinois à crête",
                    "A56" to "Lhassa Apso",
                    "A57" to "Treeing Tennessee Brindle",
                    "A58" to "Norwich Terrier",
                    "A59" to "Chien léopard catahoula",
                    "A60" to "Lurcher",
                    "A61" to "Génétique",
                    "A62" to "Chien courant d'Estonie",
                    "A63" to "Mâtin de l'Alentejo",
                    "A64" to "Braque de Weimar",
                    "A65" to "Huntaway",
                    "A66" to "Chien courant de Hygen",
                    "A67" to "Chien de Terre-Neuve",
                    "A68" to "Pinscher nain",
                    "A69" to "Braque italien",
                    "A70" to "Lévrier de Pharaon",
                    "A71" to "Bouvier de l'Appenzell",
                    "A72" to "Pinscher allemand",
                    "A73" to "Field Spaniel",
                    "A74" to "Lévrier russe",
                    "A75" to "Charnaigre race disparue",
                    "A76" to "Chien-loup de Saarloos",
                    "A77" to "Bull Terrier",
                    "A78" to "Berger yougoslave de Charplanina",
                    "A79" to "Terrier irlandais",
                    "A80" to "Samoyède",
                    "A81" to "Berger de Bohème",
                    "A82" to "Berger allemand",
                    "A83" to "Berger Hellénique",
                    "A84" to "Dogue de Majorque",
                    "A85" to "King Shepherd",
                    "A86" to "Mastiff d'Anatolie",
                    "A87" to "Chien courant de Hamilton",
                    "A88" to "Chien de Bali",
                    "A89" to "Colley",
                    "A90" to "Beagle-harrier",
                    "A91" to "Labradinger",
                    "A92" to "Cirneco de l'Etna",
                    "A93" to "Akita américain",
                    "A94" to "Bulldog de sang bleu alpha",
                    "A95" to "Chien Corse Cursinu",
                    "A96" to "Barbet",
                    "A97" to "Lévrier grec",
                    "A98" to "Berger anglais ancestral",
                    "A99" to "Treeing Cur",
                    "A100" to "Chien thaïlandais à crête dorsale",
                    "A101" to "Chien courant suisse",
                    "A102" to "Griffon d'arrêt à poil dur Korthals",
                    "A103" to "Français blanc et orange",
                    "A104" to "Berger australien miniature",
                    "A105" to "Irish wolfhound",
                    "A106" to "Puggle",
                    "A107" to "Grand bouvier suisse",
                    "A108" to "Golden Retriever",
                    "A109" to "Cocker Spaniel américain",
                    "A110" to "Kromfohrländer",
                    "A111" to "Spitz",
                    "A112" to "Aïnou",
                    "A113" to "Jouet Manchester terrier",
                    "A114" to "Braque de l'Ariège",
                    "A115" to "English Coonhound",
                    "A116" to "Terrier anglais d'agrément noir et feu (",
                    "A117" to "Bichon bolonais",
                    "A118" to "Terrier Kerry Blue",
                    "A119" to "Labrador",
                    "A120" to "Bulldog anglais",
                    "A121" to "Border collie Border Terrier",
                    "A122" to "Affenpinscher",
                    "A123" to "King Charles Spaniel",
                    "A124" to "Sealyham Terrier",
                    "A125" to "Staffordshire Terrier américain",
                    "A126" to "Chien de cour italien",
                    "A127" to "Chien nu mexicain",
                    "A128" to "Shih Tzu",
                    "A129" to "Chien du Groenland",
                    "A130" to "Lévrier",
                    "A131" to "Zuchon, Shichon",
                    "A132" to "Berger catalan",
                    "A133" to "Setter Gordon",
                    "A134" to "Lévrier anglais",
                    "A135" to "Sabueso espagnol - voir Chien courant espagnol",
                    "A136" to "Loulou de Poméranie - voir Spitz nain",
                    "A137" to "Bouvier de l'Entlebuch",
                    "A138" to "Braque du Dupuy race disparue",
                    "A139" to "Pointer",
                    "A140" to "Buhund norvégien",
                    "A141" to "Chien courant de Schiller",
                    "A142" to "Bichon Bolonka",
                    "A143" to "Bullmastiff",
                    "A144" to "Cursinu",
                    "A145" to "Husky de Sakhaline",
                    "A146" to "Terrier écossais",
                    "A147" to "Chinook",
                    "A148" to "Chien paria",
                    "A149" to "Chien courant de Transylvanie",
                    "A150" to "Épagneul breton",
                    "A151" to "Lévrier persan",
                    "A152" to "Berger polonais de plaine",
                    "A153" to "Cairn Terrier",
                    "A154" to "Keeshond",
                    "A155" to "Retriever à poil bouclé",
                    "A156" to "Harrier",
                    "A157" to "Lithuanian Hound",
                    "A158" to "Chien de ferme dano-suédois",
                    "A159" to "Airedale Terrier",
                    "A160" to "Alaskan Klee Kai",
                    "A161" to "Chien courant polonais",
                    "A162" to "Mâtin espagnol",
                    "A163" to "Bangkaew de Thaïlande",
                    "A164" to "Bouledogue jouet",
                    "A165" to "Setter irlandais rouge",
                    "A166" to "Chien d'Artois",
                    "A167" to "Portail des mammifères",
                    "A168" to "Terrier tchèque",
                    "A169" to "Bichon havanais",
                    "A170" to "Colley barbu",
                    "A171" to "Chien courant du Småland",
                    "A172" to "Schillerstövare",
                    "A173" to "Dogue des Canaries",
                    "A174" to "Terrier blanc des Highlands de l'Ouest",
                    "A175" to "Grand anglo-français tricolore",
                    "A176" to "Berger belge",
                    "A177" to "Cão de Gado Transmontano",
                    "A178" to "Sussex Spaniel",
                    "A179" to "Liste de toutes les races de chiens avec des photos et des liens[archive]",
                    "A180" to "Chien-loup tchécoslovaque",
                    "A181" to "Pomsky",
                    "A182" to "Spitz de Norrbotten",
                    "A183" to "Berger de Bergame",
                    "A184" to "Chien finnois de Laponie",
                    "A185" to "Perro sin pelo del Perú - voir Chien nu du Pérou",
                    "A186" to "Yorkipoo",
                    "A187" to "Petit brabancon",
                    "A188" to "Grand anglo-français blanc et noir",
                    "A189" to "Chien d'arrêt danois ancestral",
                    "A190" to "Bouvier australien",
                    "A191" to "Chien d'arrêt portugais",
                    "A192" to "Bedlington Terrier",
                    "A193" to "Schweizer Laufhund",
                    "A194" to "Alaunt",
                    "A195" to "Berger de Majorque",
                    "A196" to "Chien d'élan norvégien gris",
                    "A198" to "Tosa",
                    "A199" to "Chien courant de Halden",
                    "A200" to "Épagneul de Münster",
                    "A201" to "Talbot race disparue",
                    "A202" to "Basset bleu de Gascogne",
                    "A203" to "Chien courant d'Istrie à poil ras",
                    "A204" to "Petit basset griffon Vendéen",
                    "A205" to "Tenterfield Terrier",
                    "A206" to "Pit Bull",
                    "A207" to "Setter irlandais rouge et blanc",
                    "A208" to "Ariégeois",
                    "A209" to "Chien courant de Virelade race disparue",
                    "A210" to "Mâtin transmontano",
                    "A211" to "Bouvier des Ardennes",
                    "A212" to "Chien courant du Nord  race disparue",
                    "A213" to "Chien de garenne des Canaries",
                    "A214" to "Chien courant grec",
                    "A215" to "Portail des canidés",
                    "A216" to "Koolie",
                    "A217" to "Stephens Cur",
                    "A218" to "Berger d'Asie centrale",
                    "A219" to "Caniche",
                    "A220" to "Lévrier portugais",
                    "A221" to "Kishu",
                    "A222" to "Chihuahua",
                    "A223" to "Caniche Royal",
                    "A224" to "Porcelaine",
                    "A225" to "Jug",
                    "A226" to "Landseer )",
                    "A227" to "Berger d'Anatolie - voir Berger Kangal",
                    "A228" to "Chien de recherche au sang de la montagne bavaroise",
                    "A229" to "Boykin Spaniel",
                    "A230" to "Épagneul springer gallois",
                    "A231" to "Berger blanc suisse",
                    "A232" to "Shar Pei",
                    "A233" to "Berger du Caucase",
                    "A234" to "Dalmatien",
                    "A235" to "Retriever à poil plat",
                    "A236" to "Lévrier des Baléares",
                    "A237" to "Terrier gallois",
                    "A238" to "Lévrier hongrois",
                    "A239" to "Épagneul tibétain",
                    "A240" to "Retriever de la baie de Chesapeake",
                    "A241" to "Braque allemand à poil court",
                    "A242" to "Schnoodle",
                    "A243" to "Chien de montagne portugais",
                    "A244" to "Griffon belge",
                    "A245" to "Mal-shi",
                    "A246" to "Berger des Shetland",
                    "A247" to "Race",
                    "A248" to "Mâtin des Pyrénées",
                    "A249" to "Briquet griffon vendéen bruno Griffon vendéen",
                    "A250" to "Coton de Tuléar",
                    "A251" to "Lévrier australien",
                    "A252" to "Grand anglo-français blanc et orange",
                    "A253" to "Manchester terrier",
                    "A254" to "Braque hongrois à poil court",
                    "A255" to "Chien courant de montagne du Monténégro",
                    "A256" to "Akbash",
                    "A257" to "Lévrier arabe",
                    "A258" to "Lévrier des Canaries",
                    "A259" to "Chien",
                    "A260" to "Braque hongrois à poil dur",
                    "A261" to "Berger Portugais",
                    "A262" to "Berger d'Artois race disparue",
                    "A263" to "Berger Croate",
                    "A264" to "Shikoku",
                    "A265" to "Teddy Roosevelt Terrier",
                    "A266" to "Berger du Karst",
                    "A267" to "Berger finnois de Laponie",
                    "A268" to "Bull Boxer",
                    "A269" to "Retriever du Labrador",
                    "A270" to "Texas Heeler",
                    "A271" to "Bichon Yorkie",
                    "A272" to "Lévrier Caravan hound",
                    "A273" to "Lévrier polonais",
                    "A274" to "Lévrier azawakh",
                    "A275" to "Akita Inu",
                    "A276" to "Maltipoo",
                    "A277" to "Chien d'eau américain",
                    "A278" to "Chien d'élan suédois",
                    "A279" to "Goldendoodle",
                    "A280" to "Laika de Iakoutie",
                    "A281" to "Cockapoo",
                    "A282" to "Chien norvégien de macareux",
                    "A283" to "Berger roumain",
                    "A284" to "Épagneul de Saint-Usuge",
                    "A285" to "Petit Münsterländer",
                    "A286" to "Basset hound",
                    "A287" to "Cavoodle",
                    "A288" to "Bull Terrier",
                    "A289" to "Société centrale canine [archive]",
                    "A290" to "Grand griffon vendéen",
                    "A291" to "Teckel",
                    "A292" to "Billy",
                    "A293" to "Chien africain",
                    "A294" to "Basset suédois",
                    "A295" to "Cavalier roi Charles Spaniel",
                    "A296" to "Mountain Cur",
                    "A297" to "Griffon bleu de Gascogne",
                    "A298" to "Berger Himalayen",
                    "A299" to "Skye Terrier",
                    "A300" to "Ratier de Prague",
                    "A301" to "Berger basque",
                    "A302" to "Griffon d'arrêt tchèque",
                    "A303" to "Labradoodle",
                    "A304" to "Aïdi",
                    "A305" to "Chien de montagne des Pyrénées",
                    "A306" to "Staffordshire Bull Terrier ou Staffie",
                    "A307" to "Lévrier de soie",
                    "A308" to "Chien à loutre",
                    "A309" to "Spitz italien",
                    "A310" to "Cimarron uruguayen",
                    "A311" to "Lévrier Taïgan",
                    "A312" to "Terrier australien à poil soyeux",
                    "A313" to "Brachet de Styrie à poil dur",
                    "A314" to "Jindo coréen",
                    "A315" to "Chien nu du Pérou",
                    "A316" to "Français blanc et noir",
                    "A317" to "Chien courant de Posavatz",
                    "A318" to "Boxer",
                    "A319" to "Laïka de Sibérie occidentale",
                    "A320" to "Berger d'Auvergne",
                    "A321" to "Alano espagnol",
                    "A322" to "Chien de perdrix de Drente",
                    "A323" to "Chien courant italien",
                    "A324" to "Lévrier whippet",
                    "A325" to "Ratonero Bodeguero Andaluz",
                    "A326" to "Berger des Cévennes race disparue",
                    "A327" to "Domestication",
                    "A328" to "Chien courant norvégien",
                    "A329" to "Kerry beagle",
                    "A330" to "Colley à poil court",
                    "A331" to "Chien suédois de Laponie",
                    "A332" to "Puli",
                    "A333" to "Bulldog Americain",
                    "A334" to "Kuvasz",
             "A336" to "Épagneul picard",
                    "A337" to "Schnauzer",
                    "A338" to "Berger du Languedoc Farou, race disparue",
                    "A339" to "Braque de Burgos",
                    "A340" to "Welsh Corgi Cardigan",
                    "A341" to "Terrier japonais",
                    "A342" to "Mâtin belge Chien de trait belge",
                    "A343" to "Armant dog",
                    "A344" to "Estonian Hound",
                    "A345" to "Welsh Corgi Pembroke",
                    "A346" to "Chien d'eau espagnol",
                    "A347" to "Papillon - voir Épagneul nain continental papillon",
                    "A348" to "Yorkillon",
                    "A349" to "Pékinois",
                    "A350" to "Bouvier australien à courte queue",
                    "A351" to "Chien d'élan norvégien noir",
                    "A352" to "Chien d'arrêt frison",
                    "A353" to "Chien d'oysel allemand",
                    "A354" to "Mackenzie River husky",
                    "A355" to "Berger des Tatras",
                    "A356" to "Basset de Westphalie",
                    "A357" to "Chien courant espagnol",
                    "A358" to "Redbone Coonhound",
                    "A359" to "Jack Russell Terrier",
                    "A360" to "Kuchi dog",
                    "A361" to "Husky sibérien",
                    "A362" to "Lévrier Bakhmull",
                    "A363" to "Berger de Savoie ou berger des Alpes",
                    "A364" to "Kelpie australien",
                    "A365" to "Malamute d'Alaska",
                    "A366" to "Chien d'eau portugais",
                    "A367" to "Chien de recherche au sang du Hanovre",
                    "A368" to "Berger des Pyrénées",
                    "A369" to "Terrier brésilien",
                    "A370" to "Français tricolore",
                    "A371" to "Braque du Bourbonnais",
                    "A372" to "Chien du Haut-Poitou race disparue",
                    "A373" to "Yorkshire Terrier",
                    "A374" to "Griffon bruxellois",
                    "A375" to "Chien d'eau frison",
                    "A376" to "Esquimau américain",
                    "A377" to "Chien Afghan",
                    "A378" to "Alangu Mastiff",
                    "A379" to "Plott Hound",
                    "A380" to "Bouledogue français",
                    "A381" to "Saint-bernard",
                    "A382" to "Grand basset griffon vendéen",
                    "A383" to "Épagneul japonais",
                    "A384" to "Chien noir et feu pour la chasse au raton laveur",
                    "A385" to "Terrier du Révérend Russel",
                    "A386" to "Petit chien russe",
                    "A387" to "Kooikerhondje",
                    "A388" to "Terrier noir",
                    "A389" to "Berger de Bosnie-Herzégovine et de Croatie",
                    "A390" to "Chien courant d'Istrie à poil dur",
                    "A391" to "Rhodesian Ridgeback",
                    "A392" to "Épagneul français",
                    "A393" to "Lévrier Rampur",
                    "A394" to "Foxhound anglais",
                    "A395" to "Petit chien hollandais de chasse - voir Kooikerhondje",
                    "A396" to "Petit chien courant suisse",
                    "A397" to "Longdog",
                    "A398" to "Laïka de Sibérie orientale",
                    "A399" to "Eurasier",
                    "A400" to "Chien de Taïwan",
                    "A401" to "Alopekis",
                    "A402" to "Sheeoadoodle",
                    "A403" to "Lévrier irlandais",
                    "A404" to "Bullenbeieer",
                    "A405" to "Perro fino Colombiano",
                    "A406" to "Dandie Dinmont Terrier",
                    "A407" to "Poitevin",
                    "A408" to "Chien d'arrêt italien à poil dur",
                    "A409" to "Bulldog Australien",
                    "A410" to "Gascon saintongeois",
                    "A411" to "Colley à poil long",
                    "A412" to "Petit lévrier italien",
                    "A413" to "Griffon fauve de Bretagne",
                    "A414" to "Berger de la Maremme et des Abruzzes",
                    "A415" to "Griffon nivernais",
                    "A416" to "Bichon à poil frisé",
                    "A417" to "Petit bleu de Gascogne",
                    "A418" to "Smous des Pays-Bas",
                    "A419" to "Esquimau canadien",
                    "A420" to "Patterdale Terrier",
                    "A421" to "Kyi Leo",
                    "A422" to "Brachet polonais",
                    "A423" to "Komondor",
                    "A424" to "Bouche noire cur",
                    "A425" to "Chien d'arrêt allemand à poil dur",
                    "A426" to "Basset ardennais race disparue",
                    "A427" to "Dogue du Tibet",
                    "A428" to "Pudelpointer",
                    "A429" to "Setter anglais",
                    "A430" to "Chien chanteur",
                    "A431" to "Chien courant slovaque",
                    "A432" to "Carlin",
                    "A433" to "Spitz des Visigoths",
                    "A434" to "Tchouvatch slovaque",
                    "A435" to "Levesque race disparue",
                    "A436" to "Terrier de Boston",
                    "A437" to "Terrier Glen of Imaal",
                    "A438" to "Basset d'Artois",
                    "A439" to "Anglo-Français de petite vénerie",
                    "A440" to "Bouvier des Flandres",
                    "A441" to "Shih-poo",
                    "A442" to "Lancashire Heeler",
                    "A443" to "Fox Terrier",
                    "A444" to "Kyi apso tibétain",
                    "A445" to "Treeing Walker Coonhound",
                    "A446" to "Brachet tyrolien",
                    "A447" to "Schapendoes néerlandais",
                    "A448" to "Braque slovaque à poil dur",
                    "A449" to "Chien d'eau irlandais",
                    "A450" to "Sapsali",
                    "A451" to "Griffon boulet à poil laineux",
                    "A452" to "Lévrier afghan",
                    "A453" to "Chien d'eau romagnol",
                    "A454" to "Biewer Yorkshire",
                    "A455" to "Berger americain miniature",
                    "A456" to "Braque Saint-Germain",
                    "A457" to "Dingo Américain",
                    "A458" to "Chien de Canaan",
                    "A459" to "Goldador",
                    "A460" to "Intimidateur américain",
                    "A461" to "Labernois",
                    "A462" to "Spitz japonais",
                    "A463" to "Pumi",
                    "A464" to "Schipperke",
                    "A465" to "Bruno du Jura type Saint-Hubert",
                    "A466" to "Phalène",
                    "A467" to "Sporting Lucas Terrier",
                    "A468" to "Basset fauve de Bretagne",
                    "A469" to "Chien courant serbe ou chien courant des Balkans",
                    "A470" to "Chien d'ours de Carélie",
                    "A471" to "Lévrier espagnol",
                    "A472" to "Berger australien",
                    "A473" to "Chien courant de Bosnie à poil dur dit Barak",
                    "A474" to "Chien courant finlandais",
                    "A475" to "Retriever de la Nouvelle-écosse",
                    "A476" to "Chien noir et feu pour la chasse au raton laveur",
                    "A477" to "Clumber Spaniel",
                    "A478" to "Mâtin napolitain",
                    "A479" to "Épagneul continental",
                    "A480" to "Boerboel",
                    "A482" to "Braque français",
                    "A483" to "Griffon de Bresse",
                    "A484" to "Mastiff",
                    "A485" to "Spitz finlandais",
                    "A486" to "Bluetick coonhound",
                    "A487" to "Basset des Alpes",
                    "A488" to "Traîneau de Sibérie de Seppala",
                    "A489" to "Beaglier",
                    "A490" to "Berger bulgare",
                    "A491" to "Berger de Russie méridionale ou berger d'Ukraine",
                    "A492" to "Old English Bulldog",
                    "A493" to "Chien courant tricolore serbe",
                    "A494" to "Laika russo-européen",
                    "A495" to "Terrier glabre américain",
                    "A496" to "Brachet allemand",
                    "A497" to "Grand bleu de Gascogne",
                    "A498" to "Braque portugais",
                    "A499" to "Shiba Inu",
                    "A500" to "Dogue de Bordeaux",
                    "A501" to "Berger de Brie",
                    "A502" to "Basset artésien normand",
                    "A503" to "Leonberg"
            )

    private val codePattern = Regex("^A\\d+$")

    fun resolveRaceCode(especeValue: String?, raceValue: String): String? {
        if (especeValue.isNullOrBlank()) return null
        val trimmedRace = raceValue.trim()
        if (!codePattern.matches(trimmedRace)) return null

        val espece = Espece.getFromString(especeValue.trim()) ?: return null
        return when (espece) {
            Espece.CHAT -> catRaceMap[trimmedRace]
            Espece.CHIEN -> dogRaceMap[trimmedRace]
            else -> null
        }
    }
}
